external_components:
  - source:
      type: git
      url: https://github.com/hellosamblack/esphome-configurations
      ref: main
    components: [ sam_seeed_mr60bha2 ]
    refresh: 0min

sam_seeed_mr60bha2:

binary_sensor:
  - platform: sam_seeed_mr60bha2
    has_target:
      name: "Person Detected (Raw)"
      id: person_detected_raw
      device_class: occupancy
      entity_category: "diagnostic"

  - platform: template
    id: person_detected
    name: "Person Detected"
    device_class: occupancy
    lambda: |-
      return id(person_detected_raw).state;
    filters:
      - delayed_off: 60s

light:
  - platform: esp32_rmt_led_strip
    id: led_ring
    name: "Front LED"
    pin: GPIO1
    num_leds: 1
    rgb_order: GRB
    chipset: ws2812
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          transition_length: 500ms
          update_interval: 2s
      - pulse:
          name: "Asymmetrical Pulse"
          transition_length:
            on_length: 1s
            off_length: 500ms
          update_interval: 1.5s
      - lambda:
          name: "Distance Visualization"
          update_interval: 250ms
          lambda: |-
            if (id(person_detected_raw).state) {
              float distance_var = id(distance).state;
              float brightness = (distance_var / 10.0) * 89.0 + 11.0; // Map distance 0-10 to brightness 11-100
              int red = (int)(255 * (1 - (distance_var / 10.0))); // Red decreases as distance increases
              int green = (int)(255 * (distance_var / 10.0)); // Green increases as distance increases
              int blue = (int)(255 * (distance_var / 10.0)); // Blue increases as distance increases
              auto call = id(led_ring).turn_on();
              call.set_brightness(brightness / 100.0);
              call.set_rgb(red / 255.0, green / 255.0, blue / 255.0);
              call.perform(); 
            } else {
              id(led_ring).turn_off();
            }


sensor:
  - platform: bh1750
    name: "Ambient Light"
    address: 0x23
    update_interval: 1s
    accuracy_decimals: 0
    device_class: illuminance
    id: illuminance
    state_class: measurement
    filters:
      - or:
          - delta: 10
          - exponential_moving_average:
              #Closer to 1.0: Less smoothing, more responsive to recent changes. The output will more closely follow the raw sensor data.
              #Closer to 0.0: More smoothing, less responsive to recent changes. The output will be more stable, but changes will be reflected more slowly.
              alpha: 0.2  # Adjust alpha value (0.0 - 1.0)
              send_every: 15


  - platform: sam_seeed_mr60bha2
    id: sam_seeed_mr60bha2_id
    breath_rate:
      name: "Respiratory Rate"
      id: respiratory_rate
      state_class: measurement
      # filters:
      #   - or:
      #     - delta: 2
      #     - exponential_moving_average: 
      #         alpha: .2
      #         send_every: 5
    heart_rate:
      name: "Heart Rate"
      id: heart_rate
      state_class: measurement
      # filters:
      #   - or:
      #     - delta: 3
      #     - exponential_moving_average: 
      #         alpha: .2
      #         send_every: 5
    distance:
      name: "Distance"
      id: distance
      unit_of_measurement: ft
      accuracy_decimals: 1
      filters:
        - multiply: .0328084 # Convert centimeters to feet
        - filters:
          - delta: .5
        # - or:
        #   - delta: 1
        #   - exponential_moving_average: 
        #       alpha: .2
        #       send_every: 5
    num_targets:
      name: "Number of Targets"
      id: number_of_targets
      unit_of_measurement: "People"
      state_class: measurement
      accuracy_decimals: 0
      # filters:
      # - delta: 1