esphome:
  platformio_options:
    board_upload.maximum_size: 4194304

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB # upload.flash_size
  framework:
    type: esp-idf
    version: latest

logger:
  level: DEBUG
  hardware_uart: USB_SERIAL_JTAG
  baud_rate: 0

wifi:
  #id: !extend wifi_id
  enable_btm: True
  enable_rrm: True
  
captive_portal:

# For XIAO ESP32C6 Onboard LED
# light:
#   - platform: status_led
#     name: "Switch state"
#     pin: GPIO15

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true
  id: bus_a

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 17
  tx_pin: 16
  parity: NONE
  stop_bits: 1