esphome:
  name: $device_name
  friendly_name: $friendly_name
  platformio_options:
    framework: $esphome_platformio_options_framework
    board_build.flash_mode: $esphome_platformio_options_board_build_flash_mode
    board_build.mcu: $esphome_platformio_options_board_build_mcu


logger:
  #https://github.com/agittins/bermuda/wiki/ESPHome-Configurations
  baud_rate: 0  # 0 Enables logging, but disables serial-port logging to free CPU and memory if set to zero
  #Otherwise 9600 seems to be common
#More logging
  level: DEBUG
#Less logging
#level: INFO
#logs:
#  esp32_ble_tracker: VERY_VERBOSE

api:
  encryption:
    key: $api_encryption_key
  #https://github.com/agittins/bermuda/wiki/ESPHome-Configurations
  # Only enable BLE tracking when wifi is up and api is connected
  # Gives single-core ESP32-C3 devices time to manage wifi and authenticate with api
  on_client_connected:
     - esp32_ble_tracker.start_scan:
        continuous: true
  # Disable BLE tracking when there are no api connections live
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:

ota:
  platform: esphome
  password: $ota_password

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $device_name
    password: !secret wifi_password
  #use_address: $static_ip
  #https://esphome.io/components/wifi.html#wifi-power-save-mode
  power_save_mode: light
  networks:
  - ssid: !secret wifi_office_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_bedroom_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_dining_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_entry_ssid
    password: !secret wifi_password

mdns:
  disabled: false

external_components:
  source: github://hellosamblack/ESPHome-Configurations
  components: [ wifi_csi ]

wifi_csi:
  id: csi_motion
  name: WiFi Motion detected
  timing: 100ms
  buffer_size: 100
  hysteresis: 5
  filters:
    - delayed_off: 300000ms
    - delayed_on: 500ms