esphome:
  name: $device_name
  friendly_name: $friendly_name

bk72xx:
  board: generic-bk7231t-qfn32-tuya

#Seems to be causing a compilation error
#web_server:

external_components:
  source: github://hellosamblack/ESPHome-Configurations
  components: [ wifi_csi ]

wifi_csi:
  id: csi_motion
  name: WiFi Motion detected
  timing: 100ms
  buffer_size: 100
  hysteresis: 5
  filters:
    - delayed_off: 300000ms
    - delayed_on: 500ms

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version