esphome:
  name: $device_name
  friendly_name: $friendly_name
  area: $area
  project:
    name: $project_name
    version: $project_version

logger:
  #id: logger_id
  #https://github.com/agittins/bermuda/wiki/ESPHome-Configurations
  baud_rate: 0  # 0 Enables logging, but disables serial-port logging to free CPU and memory if set to zero
  #Otherwise 9600 seems to be common
#More logging
  level: DEBUG
#Less logging
#level: INFO
#logs:
#  esp32_ble_tracker: VERY_VERBOSE

api:
  #id: api_id
  encryption:
    key: $api_encryption_key

ota:
  platform: esphome
  password: $ota_password

#web_server:


wifi:
  #id: wifi_id
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $device_name
    password: !secret wifi_password
  #use_address: $static_ip
  #https://esphome.io/components/wifi.html#wifi-power-save-mode
  power_save_mode: light
  networks:
  - ssid: !secret wifi_office_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_bedroom_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_dining_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_entry_ssid
    password: !secret wifi_password

mdns:
  disabled: false