esphome:
  name: $device_name
  friendly_name: $friendly_name

bk72xx:
  board: generic-bk7231t-qfn32-tuya

#Seems to be causing a compilation error
#web_server:

external_components:
  source: github://hellosamblack/ESPHome-Configurations
  components: [ wifi_csi ]

wifi_csi:
  id: csi_motion
  name: WiFi Motion detected
  timing: 100ms
  buffer_size: 100
  hysteresis: 5
  filters:
    - delayed_off: 300000ms
    - delayed_on: 500ms

binary_sensor:

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version


output:
  - platform: libretiny_pwm
    id: output_red
    pin: P9
  - platform: libretiny_pwm
    id: output_green
    pin: P24
  - platform: libretiny_pwm
    id: output_blue
    pin: P26
  - platform: libretiny_pwm
    id: output_cold
    pin: P6
    frequency: 2000 Hz
  - platform: libretiny_pwm
    id: output_warm
    pin: P8
    frequency: 2000 Hz

light:
  - platform: rgbww
    id: light_rgbww
    name: Light
    color_interlock: true
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 4000 K
    #warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold
    warm_white: output_warm
    constant_brightness: true
